kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: fleet-drift-sample
  namespace: fleet-default
labels:
  owner-repo: fleet-drift-sample
spec:
  repo: https://github.com/raif-ahmed/fleet-drift-sample
  branch: main
  
  paths:
    - apps/manifests
  
  targets:
    - name: all-downstream
      clusterSelector: {}
  
  pollingInterval: 15s

  # Paused  causes changes in Git to not be propagated down to the clusters but
  # instead mark resources as OutOfSync
  # paused: false

  # Increment this number to force a redeployment of contents from Git
  #
  # forceSyncGeneration: 0
  correctDrift:
    enabled: true
  # KeepResources specifies if the resources created must be kept after deleting the *GitRepo*.
  keepResources: false
  # DeleteNamespace specifies if the namespace created must be deleted after deleting the *GitRepo*.
  deleteNamespace: true